# Generated by Django 4.0.1 on 2022-10-28 02:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0003_rename_identificacao_equipamento_idf'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='agenda',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 2, 0, 45, 355866, tzinfo=utc), max_length=30, verbose_name='Agendamento da Ferramenta:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='idf',
            field=models.CharField(max_length=2, verbose_name='Código de Identificação'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='uso',
            field=models.CharField(max_length=20, verbose_name='Tipo de Uso'),
        ),
    ]
