# Generated by Django 4.0.1 on 2022-10-28 02:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0004_equipamento_agenda_alter_equipamento_idf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='agenda_entrega',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 2, 39, 32, 32289, tzinfo=utc), max_length=30, verbose_name='Agendamento da Ferramenta - Até:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='agenda',
            field=models.DateTimeField(max_length=30, verbose_name='Agendamento da Ferramenta - De:'),
        ),
    ]
