# Generated by Django 4.0.1 on 2022-10-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0007_alter_equipamento_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='agenda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='agenda_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
