# Generated by Django 4.0.1 on 2022-10-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0008_alter_equipamento_agenda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='agenda_entrega',
        ),
    ]
