# Generated by Django 4.0.1 on 2022-10-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0010_equipamento_agendat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='agendat',
        ),
    ]
