# Generated by Django 4.0.1 on 2022-10-28 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0013_alter_equipamento_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='agenda',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Agendamento da Ferramenta - De:'),
        ),
    ]
