# Generated by Django 4.0.1 on 2022-11-01 01:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0019_alter_equipamento_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='agenda',
            field=models.DateTimeField(blank=True, max_length=30, null=True, unique=True, verbose_name='Agendamento da Ferramenta - De:'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='agenda_entrega',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 1, 28, 23, 809426, tzinfo=utc), max_length=30, verbose_name='Agendamento da Ferramenta - Até:'),
            preserve_default=False,
        ),
    ]
