# Generated by Django 4.0.1 on 2022-11-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0023_alter_equipamento_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='agenda',
            field=models.DateTimeField(blank=True, default=True, max_length=30, null=True, unique=True, verbose_name='Agendamento da Ferramenta - De:'),
        ),
    ]
