# Generated by Django 4.0.1 on 2022-12-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0027_agendarequipamento_remove_equipamento_agenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='agenda',
            field=models.DateTimeField(blank=True, max_length=30, null=True, unique=True, verbose_name='Agendamento da Ferramenta - De:'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='agenda_entrega',
            field=models.DateTimeField(blank=True, max_length=30, null=True, unique=True, verbose_name='Agendamento da Ferramenta - Até:'),
        ),
    ]
