# Generated by Django 4.1.4 on 2022-12-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0028_equipamento_agenda_equipamento_agenda_entrega'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendarEquipamento',
        ),
    ]
