# Generated by Django 4.1.4 on 2022-12-12 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0029_delete_agendarequipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='nomeuser',
            field=models.CharField(default=django.utils.timezone.now, max_length=70, verbose_name='Nome do Usuário:'),
            preserve_default=False,
        ),
    ]
