# Generated by Django 4.0.1 on 2022-10-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipamentos',
            new_name='Equipamento',
        ),
    ]
