# Generated by Django 4.0.1 on 2022-10-28 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0009_remove_equipamento_agenda_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='agendat',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 10, 28, 14, 11, 33, 765086, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
