# Generated by Django 4.0.1 on 2022-10-28 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0011_remove_equipamento_agendat'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='agenda_entrega',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 14, 19, 58, 636173, tzinfo=utc), max_length=30, verbose_name='Agendamento da Ferramenta - Até:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='agenda',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 14, 20, 12, 307427, tzinfo=utc), max_length=30, verbose_name='Agendamento da Ferramenta - De:'),
            preserve_default=False,
        ),
    ]
