# Generated by Django 4.0.1 on 2022-11-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0021_alter_equipamento_agenda_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='agenda_entrega',
            field=models.DateTimeField(blank=True, max_length=30, null=True, unique=True, verbose_name='Agendamento da Ferramenta - Até:'),
        ),
    ]
