# Generated by Django 4.0.1 on 2022-11-01 01:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0022_alter_equipamento_agenda_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='agenda',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 1, 31, 41, 876315, tzinfo=utc), max_length=30, verbose_name='Agendamento da Ferramenta - De:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='agenda_entrega',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 1, 31, 49, 572915, tzinfo=utc), max_length=30, verbose_name='Agendamento da Ferramenta - Até:'),
            preserve_default=False,
        ),
    ]
